#
# Autogenerated by Thrift Compiler (0.10.0)
#
# DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
#
require 5.6.0;
use strict;
use warnings;
use Thrift;

package exampleThrift::Country;
use constant AMERICA => 0;
use constant JAPAN => 1;
use constant CANADA => 2;
package exampleThrift::Person;
use base qw(Class::Accessor);
exampleThrift::Person->mk_accessors( qw( name age country hobby ) );

sub new {
  my $classname = shift;
  my $self      = {};
  my $vals      = shift || {};
  $self->{name} = undef;
  $self->{age} = undef;
  $self->{country} = undef;
  $self->{hobby} = undef;
  if (UNIVERSAL::isa($vals,'HASH')) {
    if (defined $vals->{name}) {
      $self->{name} = $vals->{name};
    }
    if (defined $vals->{age}) {
      $self->{age} = $vals->{age};
    }
    if (defined $vals->{country}) {
      $self->{country} = $vals->{country};
    }
    if (defined $vals->{hobby}) {
      $self->{hobby} = $vals->{hobby};
    }
  }
  return bless ($self, $classname);
}

sub getName {
  return 'Person';
}

sub read {
  my ($self, $input) = @_;
  my $xfer  = 0;
  my $fname;
  my $ftype = 0;
  my $fid   = 0;
  $xfer += $input->readStructBegin(\$fname);
  while (1) 
  {
    $xfer += $input->readFieldBegin(\$fname, \$ftype, \$fid);
    if ($ftype == TType::STOP) {
      last;
    }
    SWITCH: for($fid)
    {
      /^1$/ && do{      if ($ftype == TType::STRING) {
        $xfer += $input->readString(\$self->{name});
      } else {
        $xfer += $input->skip($ftype);
      }
      last; };
      /^2$/ && do{      if ($ftype == TType::I32) {
        $xfer += $input->readI32(\$self->{age});
      } else {
        $xfer += $input->skip($ftype);
      }
      last; };
      /^3$/ && do{      if ($ftype == TType::I32) {
        $xfer += $input->readI32(\$self->{country});
      } else {
        $xfer += $input->skip($ftype);
      }
      last; };
      /^4$/ && do{      if ($ftype == TType::STRING) {
        $xfer += $input->readString(\$self->{hobby});
      } else {
        $xfer += $input->skip($ftype);
      }
      last; };
        $xfer += $input->skip($ftype);
    }
    $xfer += $input->readFieldEnd();
  }
  $xfer += $input->readStructEnd();
  return $xfer;
}

sub write {
  my ($self, $output) = @_;
  my $xfer   = 0;
  $xfer += $output->writeStructBegin('Person');
  if (defined $self->{name}) {
    $xfer += $output->writeFieldBegin('name', TType::STRING, 1);
    $xfer += $output->writeString($self->{name});
    $xfer += $output->writeFieldEnd();
  }
  if (defined $self->{age}) {
    $xfer += $output->writeFieldBegin('age', TType::I32, 2);
    $xfer += $output->writeI32($self->{age});
    $xfer += $output->writeFieldEnd();
  }
  if (defined $self->{country}) {
    $xfer += $output->writeFieldBegin('country', TType::I32, 3);
    $xfer += $output->writeI32($self->{country});
    $xfer += $output->writeFieldEnd();
  }
  if (defined $self->{hobby}) {
    $xfer += $output->writeFieldBegin('hobby', TType::STRING, 4);
    $xfer += $output->writeString($self->{hobby});
    $xfer += $output->writeFieldEnd();
  }
  $xfer += $output->writeFieldStop();
  $xfer += $output->writeStructEnd();
  return $xfer;
}

1;
